package prompts

import (
	"encoding/json"
	"fmt"
	"strings"
)

// FileSystemRules defines the standard path jail instructions.
const FileSystemRules = `
STRICT WORKSPACE RULES:
1. FILESYSTEM: All file paths MUST be relative to the workspace root. Example: to read 'task.md', use 'task.md'.`

const ToolManualHeader = "# TOOL INTERFACE"

// HasToolManual checks if the tool instructions are already present in the content.
func HasToolManual(content string) bool {
	return strings.Contains(content, ToolManualHeader)
}

// InjectToolManual merges tool instructions into existing content, ensuring they are only added once.
func InjectToolManual(content string, instructions string) string {
	if HasToolManual(content) {
		return content
	}
	if content == "" {
		return instructions
	}
	return fmt.Sprintf("%s\n\n%s", content, instructions)
}

// ToolInfo is a simplified version of a tool's schema for template generation.
type ToolInfo struct {
	Name        string
	Description string
	Parameters  any
}

// BuildToolManual generates the dynamic technical manual for available tools.
// It uses the unified JSON array format for consistency.
func BuildToolManual(tools []ToolInfo) string {
	if len(tools) == 0 {
		return ""
	}
	var sb strings.Builder
	for _, t := range tools {
		sb.WriteString(fmt.Sprintf("### %s\n%s\n", t.Name, t.Description))
		params, _ := json.MarshalIndent(t.Parameters, "", "  ")
		sb.WriteString(fmt.Sprintf("Schema:\n```json\n%s\n```\n\n", string(params)))
	}
	return fmt.Sprintf(UnifiedToolManual, sb.String())
}

// UnifiedToolManual defines the ONE canonical tool calling format using XML boundaries.
const UnifiedToolManual = `## TOOL INTERFACE
You operate in a strict Reason -> Act -> Observe loop. 
To execute a tool, you MUST wrap a single valid JSON object inside <tool_call> tags.
Do not use markdown block formatting (` + "```json" + `) inside the tags.

Format:
Thought: [Your reasoning here]
Action:
<tool_call>
{
  "tool": "TOOL_NAME",
  "args": {
    "ARG_NAME": "VALUE"
  }
}
</tool_call>

### Rules
1. **Parallel Tool Execution**: Batch related actions into a single response using multiple <tool_call> tags to improve efficiency.
2. Use ONLY the tools listed below.
3. If a tool fails, you will receive the error. Fix it in your next turn.
4. Finalization: You are not finished until you call 'submit_final_answer'. 
    - **Thought**: Use this for your internal reasoning (e.g., "I have all data, I will now finalize").
    - **Action**: Use 'submit_final_answer'. The 'summary' argument MUST be the actual comprehensive report containing all raw data, tables, and findings.

### Available Tools
%s`

// DefaultRules is the operational protocol injected into the system prompt.
const DefaultRules = `You are an autonomous agent with access to tools. Your job is to complete the given task by using tools.

RULES:
1. ReAct Loop: You MUST use the Thought -> Action sequence.
2. Use tools to act. Do not describe what you would do — do it via the Action block.
3. NO UI IMITATION: Never output emojis, "Executing...", or technical status markers to simulate tool execution. These are generated by the system. You only output your internal Thought and the formal <tool_call> block.
4. Verify results. After each action, check the output before proceeding.
5. Loop Protection: If a tool returns a repetition warning, DO NOT retry. Change your approach or finalize with available data.
6. Finalization: When finished, call 'submit_final_answer'. 
    - The 'summary' argument is the FINAL PRODUCT seen by the user. 
    - It MUST include ALL requested data (e.g., full file contents, execution outputs, du tables).
7. BEST PRACTICE: Always start by verifying your environment. If you need to run code, use 'execute_terminal_command' to check for required runtimes (e.g., node, tsc, python) in your first turn.
`

// AssembleSystemPrompt aggregates the core operational constitution with any workspace-specific rules.
func AssembleSystemPrompt(customRules string) string {
	prompt := DefaultRules
	if customRules != "" && strings.TrimSpace(customRules) != strings.TrimSpace(DefaultRules) {
		prompt += "\n\nWORKSPACE-SPECIFIC RULES:\n" + customRules
	}
	return prompt
}

// DefaultHeartbeat defines a generic placeholder automation task.
const DefaultHeartbeat = `# Heartbeat Task
# Add your instructions here.
Example: Scan the local directory and list files.
`

// DefaultAgentPrompt defines the basic persona for the interactive workspace assistant.
const DefaultAgentPrompt = `# Workspace Agent
You are the interactive assistant for this workspace. Use the available tools to help the user.
You have access to the local filesystem and terminal.
Guidelines:
1. Be concise.
2. Prefer using tools to gather information before answering.
3. Stay within the authorized workspace boundaries.`

// LocalAssistantPrompt defines the persona for the LocalToolRegistry.
const LocalAssistantPrompt = DefaultRules

// DefaultWorkspaceConfig defines a clean, empty configuration for new workspaces.
const DefaultWorkspaceConfig = `model: ""
temperature: 0.7
automations: []`

const AutomationMarker = "TASK: You are an autonomous agent"

func IsAutomationTask(content string) bool {
	return strings.Contains(content, AutomationMarker)
}

// Replace the Sieve system message in agent.go (inside the totalChars > 15000 block):
const SieveSystemNote = "[System Note: History distilled to save context. DO NOT repeat your reasoning; focus ONLY on the immediate next Action. Continue your task.]"

// AutomationDuplicateNagPrompt is injected when a model repeats reasoning without acting.
const AutomationDuplicateNagPrompt = "SYSTEM CRITICAL: You are repeating yourself. STOP THINKING AND ACT.\n\n" +
	"YOU MUST START YOUR RESPONSE WITH THE CHARACTER '<'. NO PREAMBLE. NO EXPLANATION.\n" +
	"PATTERN:\n" +
	"<tool_call>\n" +
	"{\n" +
	"  \"tool\": \"TOOL_NAME\",\n" +
	"  \"args\": { \"ARG\": \"VALUE\" }\n" +
	"}\n" +
	"</tool_call>"

// AutomationNagPrompt is sent when a model outputs text without any tool calls.
const AutomationNagPrompt = "SYSTEM ERROR: NO ACTION DETECTED. You are monologuing.\n\n" +
	"YOU MUST START YOUR RESPONSE WITH THE CHARACTER '<'. NO PREAMBLE. NO EXPLANATION.\n" +
	"PATTERN:\n" +
	"<tool_call>\n" +
	"{\n" +
	"  \"tool\": \"TOOL_NAME\",\n" +
	"  \"args\": { \"ARG\": \"VALUE\" }\n" +
	"}\n" +
	"</tool_call>"

// AutomationRejectedSubmissionPrompt is sent when a model tries to call submit_final_answer along with other tools.
const AutomationRejectedSubmissionPrompt = "REJECTED: 'submit_final_answer' cannot be called in the same turn as other tools. " +
	"Complete the task. You are not finished until you successfully call the 'submit_final_answer' tool. " +
	"YOU MUST INCLUDE ALL REQUESTED OUTPUTS (Visualizations, Data, Results) IN THE SUMMARY. " +
	"FAILURE TO PROVIDE THESE IN THE FINAL SUMMARY IS A TASK FAILURE. " +
	"IMPORTANT: Your summary MUST include ALL data requested in the task (e.g., file contents, tree visualizations, execution outputs)."

// It asks the model to output its intended actions as a JSON array so the backend
// can execute the plan directly without relying on XML parsing.
const AutomationJSONPlanPrompt = `XML tool calling failed. Switch to JSON PLAN MODE.
Now output your full plan as a JSON array so the system can execute it.

Output ONLY a JSON array. No text before or after. Each element must have "tool" and "args" fields.

  {"tool": "execute_terminal_command", "args": {"command": "mkdir -p project/src"}},
  {"tool": "write_file", "args": {"path": "project/src/main.ts", "content": "console.log('hello')"}},
  {"tool": "execute_terminal_command", "args": {"command": "node project/src/main.js"}},
  {"tool": "submit_final_answer", "args": {"summary": "Task complete"}}
]`

// AutomationTaskPrompt is the user-facing task message for autonomous agents.
const AutomationTaskPrompt = AutomationMarker + ` in workspace '%s'.
Execute the instructions found in '%s':
---
%s
---

Use your tools to complete every step. Call submit_final_answer when done.`
