<script setup lang="ts">
import { computed } from 'vue'
import { marked } from 'marked'

const props = defineProps<{
  content: string
}>()

const htmlContent = computed(() => {
  if (!props.content) return ''
  
  let raw = props.content;
  
  // Smart Unwrapper: detect and strip redundant top-level markdown blocks 
  // that were baked into history or generated by less-compliant models.
  // We look for a block that starts with ``` and ends with ```
  const trimmed = raw.trim();
  const match = trimmed.match(/^```(?:markdown|text)?\n([\s\S]*)\n```$/i);
  if (match && match[1]) {
    raw = match[1];
  }

  return marked(raw, {
    gfm: true,
    breaks: true,
  })
})
</script>

<template>
  <!-- Use prose-invert but with custom overrides for ultra-compact ide scale -->
  <div class="markdown-body prose prose-invert max-w-none text-[12px] leading-tight" v-html="htmlContent"></div>
</template>

<style scoped lang="postcss">
.markdown-body {
  @apply text-gray-300 antialiased;
}

/* Tighter spacing for ide layout */
.markdown-body :deep(p) {
  @apply mb-1 mt-0;
}

.markdown-body :deep(h1), 
.markdown-body :deep(h2), 
.markdown-body :deep(h3) {
  @apply text-gray-100 font-bold mt-4 mb-2 tracking-tight;
}

.markdown-body :deep(h3) { @apply text-[13px]; }
.markdown-body :deep(h2) { @apply text-[14px]; }
.markdown-body :deep(h1) { @apply text-[16px]; }

/* Ensure code blocks look like terminal windows */
.markdown-body :deep(pre) {
  @apply bg-[#0d1117] border border-gray-800 rounded-lg p-5 overflow-x-auto mb-6 font-mono shadow-inner !important;
}

.markdown-body :deep(code) {
  @apply font-mono text-[0.85em] text-blue-300 bg-blue-900/10 px-1 py-0.5 rounded;
}

.markdown-body :deep(pre code) {
  @apply block p-0 bg-transparent border-0 leading-tight text-gray-300 !important;
}

/* Professional table styling */
.markdown-body :deep(table) {
  @apply w-full text-xs my-6 border-collapse;
}

.markdown-body :deep(th) {
  @apply bg-gray-800/50 text-gray-100 font-bold p-2 border border-gray-700 text-left;
}

.markdown-body :deep(td) {
  @apply p-2 border border-gray-700 text-gray-300;
}
</style>
