<script setup lang="ts">
import { computed } from 'vue'
import { renderMarkdown } from '../../../utils/markdown/renderMarkdown'

const props = defineProps<{
  content: string
}>()

const htmlContent = computed(() => {
  if (!props.content) return ''
  
  let raw = props.content;
  
  // Smart Unwrapper: detect and strip redundant top-level markdown blocks 
  // that were baked into history or generated by less-compliant models.
  // We look for a block that starts with ``` and ends with ```
  const trimmed = raw.trim();
  const match = trimmed.match(/^```(?:markdown|text)?\n([\s\S]*)\n```$/i);
  if (match && match[1]) {
    raw = match[1];
  }

  // Model-written text: rendered through the one safe markdown path (raw HTML
  // escaped, unsafe URL schemes dropped) before it reaches v-html.
  return renderMarkdown(raw)
})
</script>

<template>
  <!-- Use prose-invert but with custom overrides for ultra-compact ide scale -->
  <div class="markdown-body prose prose-invert max-w-none text-[12px] leading-tight" v-html="htmlContent"></div>
</template>

<style scoped lang="postcss">
.markdown-body {
  @apply text-secondary antialiased;
}

/* Tighter spacing for ide layout */
.markdown-body :deep(p) {
  @apply mb-1 mt-0;
}

.markdown-body :deep(h1), 
.markdown-body :deep(h2), 
.markdown-body :deep(h3) {
  @apply text-primary font-bold mt-4 mb-2 tracking-tight;
}

.markdown-body :deep(h3) { @apply text-[13px]; }
.markdown-body :deep(h2) { @apply text-[14px]; }
.markdown-body :deep(h1) { @apply text-[16px]; }

/* Ensure code blocks look like terminal windows */
.markdown-body :deep(pre) {
  @apply bg-surface-raised border border-hairline rounded-[var(--radius-sm)] p-5 overflow-x-auto mb-6 font-mono !important;
}

.markdown-body :deep(code) {
  @apply font-mono text-[0.85em] text-accent-info-text bg-accent-info/[0.08] px-1 py-0.5 rounded-[2px];
}

.markdown-body :deep(pre code) {
  @apply block p-0 bg-transparent border-0 leading-tight text-secondary !important;
}

/* Professional table styling */
.markdown-body :deep(table) {
  @apply w-full text-xs my-6 border-collapse;
}

.markdown-body :deep(th) {
  @apply bg-surface-raised text-primary font-bold p-2 border border-control text-left;
}

.markdown-body :deep(td) {
  @apply p-2 border border-control text-secondary;
}
</style>
