<script setup lang="ts">
import { computed } from 'vue'
import { renderMarkdown } from '../../../utils/markdown/renderMarkdown'
import type { MarkdownVariant } from '../../../types/ui'

// Model-written markdown. `document` (default) is for reading: answers and run
// reports at body size with room between blocks. `compact` is for secondary
// text inside the assistant's step timeline (reasoning).
const props = withDefaults(defineProps<{
  content: string
  variant?: MarkdownVariant
}>(), { variant: 'document' })

const htmlContent = computed(() => {
  if (!props.content) return ''

  let raw = props.content;

  // Smart Unwrapper: detect and strip redundant top-level markdown blocks
  // that were baked into history or generated by less-compliant models.
  // We look for a block that starts with ``` and ends with ```
  const trimmed = raw.trim();
  const match = trimmed.match(/^```(?:markdown|text)?\n([\s\S]*)\n```$/i);
  if (match && match[1]) {
    raw = match[1];
  }

  // Model-written text: rendered through the one safe markdown path (raw HTML
  // escaped, unsafe URL schemes dropped) before it reaches v-html.
  return renderMarkdown(raw)
})
</script>

<template>
  <div
    :class="['markdown-body prose prose-invert max-w-none', `markdown-body--${variant}`]"
    v-html="htmlContent"
  ></div>
</template>

<style scoped lang="postcss">
.markdown-body {
  @apply text-secondary antialiased;
}

/* ── Document: answers and reports ── */
.markdown-body--document {
  @apply text-[length:var(--text-body)] leading-[1.65];
}
.markdown-body--document :deep(> :first-child) { @apply mt-0; }
.markdown-body--document :deep(> :last-child) { @apply mb-0; }
.markdown-body--document :deep(p) { @apply my-3; }
.markdown-body--document :deep(h1),
.markdown-body--document :deep(h2),
.markdown-body--document :deep(h3),
.markdown-body--document :deep(h4) {
  @apply text-primary font-semibold tracking-tight mb-2 mt-6 leading-snug;
}
.markdown-body--document :deep(h1) { @apply text-[20px]; }
.markdown-body--document :deep(h2) { @apply text-[17px]; }
.markdown-body--document :deep(h3) { @apply text-[15px]; }
.markdown-body--document :deep(h4) { @apply text-[length:var(--text-body)]; }
.markdown-body--document :deep(ul),
.markdown-body--document :deep(ol) { @apply my-3 pl-5; }
.markdown-body--document :deep(li) { @apply my-1; }
.markdown-body--document :deep(li > p) { @apply my-1; }
.markdown-body--document :deep(blockquote) {
  @apply my-4 border-l-2 border-strong pl-4 not-italic text-secondary;
}
.markdown-body--document :deep(hr) { @apply my-6; }
.markdown-body--document :deep(pre) {
  @apply my-4 rounded-[var(--radius-sm)] border border-hairline bg-surface-raised p-3.5 font-mono text-[12.5px] leading-[1.55] overflow-x-auto !important;
}
.markdown-body--document :deep(.md-table-scroll) { @apply my-4; }
.markdown-body--document :deep(table) { @apply w-full border-collapse text-[13px]; }
.markdown-body--document :deep(th) { @apply border border-control bg-surface-raised px-3 py-2 text-left font-semibold text-primary; }
.markdown-body--document :deep(td) { @apply border border-control px-3 py-2 align-top text-secondary; }

/* ── Compact: reasoning inside the step timeline ── */
.markdown-body--compact {
  @apply text-[length:var(--text-small)] leading-snug;
}
.markdown-body--compact :deep(p) { @apply mb-1 mt-0; }
.markdown-body--compact :deep(h1),
.markdown-body--compact :deep(h2),
.markdown-body--compact :deep(h3) { @apply text-primary font-semibold mt-2 mb-1 text-[length:var(--text-small)]; }
.markdown-body--compact :deep(ul),
.markdown-body--compact :deep(ol) { @apply my-1; }
.markdown-body--compact :deep(pre) {
  @apply my-2 rounded-[var(--radius-sm)] border border-hairline bg-surface-raised p-2.5 font-mono overflow-x-auto !important;
}
.markdown-body--compact :deep(.md-table-scroll) { @apply my-2; }
.markdown-body--compact :deep(table) { @apply w-full border-collapse text-[11px]; }
.markdown-body--compact :deep(th) { @apply border border-control bg-surface-raised p-1.5 text-left text-primary; }
.markdown-body--compact :deep(td) { @apply border border-control p-1.5 text-secondary; }

/* ── Shared: tables ── */
/* The wrapper scrolls; the table keeps readable columns (min-width, wrapped long
   URLs) and grows past the wrapper on narrow screens instead of crushing to one
   word per line. min-w-0 lets the viewer shrink inside flex/grid parents. */
.markdown-body { @apply min-w-0; }
.markdown-body :deep(.md-table-scroll) {
  @apply max-w-full overflow-x-auto overscroll-x-contain;
}
.markdown-body :deep(.md-table-scroll > table) { @apply m-0 w-max min-w-full; }
.markdown-body :deep(th),
.markdown-body :deep(td) { @apply min-w-[7rem] max-w-[22rem] [overflow-wrap:anywhere]; }

/* ── Shared: code ── */
.markdown-body :deep(code) {
  @apply font-mono text-[0.86em] font-normal text-accent-info-text bg-accent-info/[0.08] px-1 py-0.5 rounded-[2px];
}
.markdown-body :deep(pre code) {
  @apply block p-0 bg-transparent border-0 text-secondary text-[inherit] leading-[inherit] !important;
}
</style>
